spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testProject_back
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: admin
  liquibase:
    change-log: db/changelog/2024/11/23-02-changelog.yaml
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: bobykboby84@gmail.com
    password: wvbr nyev zkfk zmzo
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

